// Generates presetData.ts from v2-系统/ files
// Run: node scripts/generatePresets.js
const fs = require('fs');
const path = require('path');

const SRC = 'E:/模块化学习/v2-系统';
const OUT = 'E:/模块化学习/med-learn-mobile/src/lib/presetDataContent.ts';

function walk(dir, base) {
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    const rel = path.relative(base, full).replace(/\\/g, '/');
    if (entry.isDirectory()) {
      results.push(...walk(full, base));
    } else if (entry.name.endsWith('.md')) {
      results.push(rel);
    }
  }
  return results;
}

const files = walk(SRC, SRC);
console.log(`Found ${files.length} .md files`);

let output = '// Auto-generated preset data - DO NOT EDIT\n';
output += '// Generated by scripts/generatePresets.js\n\n';
output += 'export interface PresetFile {\n';
output += '  path: string;\n';
output += '  content: string;\n';
output += '}\n\n';
output += 'export const PRESET_FILES: PresetFile[] = [\n';

for (const file of files) {
  const filePath = path.join(SRC, file);
  const content = fs.readFileSync(filePath, 'utf-8');
  // Escape backticks, backslashes, and dollar signs for template literals
  const escaped = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
  output += `  {\n`;
  output += `    path: \`${file}\`,\n`;
  output += `    content: \`${escaped}\`,\n`;
  output += `  },\n`;
}

output += '];\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, output, 'utf-8');
console.log(`Generated ${OUT} (${(output.length / 1024).toFixed(1)} KB)`);

// Also generate JSON for web lazy loading (avoids bundling ~250KB into JS)
const JSON_OUT = path.join(__dirname, '..', 'public', 'presets.json');
const jsonData = files.map(file => {
  const content = fs.readFileSync(path.join(SRC, file), 'utf-8');
  return { path: file, content };
});
fs.mkdirSync(path.dirname(JSON_OUT), { recursive: true });
fs.writeFileSync(JSON_OUT, JSON.stringify(jsonData), 'utf-8');
console.log(`Generated ${JSON_OUT} (${(jsonData.length)} files, ${(JSON.stringify(jsonData).length / 1024).toFixed(1)} KB)`);
